return {
  formatters_by_ft = {
    lua              = { "stylua" },
    css              = { "prettier" },
    scss             = { "prettier" },
    html             = { "prettier" },
    javascript       = { "prettier" },
    javascriptreact  = { "prettier" },
    typescript       = { "prettier" },
    typescriptreact  = { "prettier" },
    svelte           = { "prettier" },
    json             = { "prettier" },
    jsonc            = { "prettier" },
    yaml             = { "prettier" },
    markdown         = { "prettier" },
    typst            = { "typstyle" },
    java             = { "clang-format" },
    c                = { "clang-format" },
    nix              = { "nixfmt" },
  },
  format_on_save = {
    timeout_ms   = 500,
    lsp_fallback = true,
  },
}
